export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const LOAD_MESSAGES = "LOAD_MESSAGES";
export const LOAD_DEBUG = "LOAD_DEBUG";
export const REGISTER_SOCKET = "REGISTER_SOCKET"
export const REMOVE_SOCKET = "REMOVE_SOCKET"
